//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid ItemId { get; set; }
        public int TopicId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Introduction { get; set; }
        public string Contents { get; set; }
        public System.DateTime insertDate { get; set; }
        public System.DateTime modifiedDate { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual User User { get; set; }
    }
}
