//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int TopicId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
